name: ye conintious integration pipe hai

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login kar docker mai
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build kar docker image
        run: docker build -t gitkeeper05/testing:latest .
      - name: push kar docker registry par
        run: docker push gitkeeper05/testing:latest
